### PR TITLE
node.instance lifetime scope

### PR DESCRIPTION
**Pull request by maxzhang1985**
Add provider life time control node.instance ,when implements  Singleton or Transient.

### CODE REVIEW

**Comment by defval** [comment]
Hi @maxzhang1985 , thanks for PR. Sorry for delay, I’ll check it tonight =)

**Comment by defval** [comment]
@maxzhang1985 can you describe the problem or case you trying to resolve?

**Comment by maxzhang1985** [comment]
I want to control objects are created by define lifetime in advance.
I understand in your planing , when node.instance has value the object created only one  by singleton way  .

**Comment by defval** [comment]
Test you have submitted successfully passes even in master branch. You don't need any code changes and inject.Lifetime(). If you fix it, I could help with your request.

```text
=== RUN   TestContainer_Group
--- PASS: TestContainer_Group (0.00s)
=== RUN   TestContainer_Group/constructors_with_providerLifetime_dependency_without_errors
    --- PASS: TestContainer_Group/constructors_with_providerLifetime_dependency_without_errors (0.00s)
PASS
```

**Comment by maxzhang1985** [comment]
@defval my unit test is successfully passed.

**Comment by defval** [comment]
@maxzhang1985 

1. checkout to master branch
2. copy your test
3. remove lifecycle option
4. run it

It passes successfully. 
It means that the lifecycle option does not change the behavior of the container or test is not correct.

I think you need to start with a feature proposal to think about the API together. It can be cleaner. Create an issue for it.

**Comment by maxzhang1985** [comment]
@defval ok

**Comment by maxzhang1985** [comment]
@defval 
I check three test errors are caused by runtime.funcforpc that the generated function name is dynamic.

There are names "constructor without result" and "constructor without result" and "constructor without result" for unit test.

**Comment by maxzhang1985** [comment]
other test is correct.

> @defval
> I check three test errors are caused by runtime.funcforpc that the generated function name is dynamic.
> 
> There are names "constructor without result" and "constructor without result" and "constructor without result" for unit test.

other test is correct.

**Pull request closed without merging**
